<a href="https://colab.research.google.com/github/moggyyy4u/MiltonMog/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#1D array
np1=np.array([1,2,3,4,5,6,7,8,9,10])
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#2D array
np2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np3=np.array([[1,2,3],[4,5,6]])
np3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D array
np4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
np4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np5=np.arange(1,100,10)
np5


array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [ ]:
np6=np.zeros([2,3])
np6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np7=np.zeros([3,3,2])
np7

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np8=np.ones([3,3,2])
np8

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
#random numbers
a=np.random.rand(3,3)
a

array([[0.24030879, 0.64669166, 0.25139555],
       [0.11781877, 0.76162583, 0.43279433],
       [0.44798296, 0.55737423, 0.37482227]])

In [ ]:
b=np.random.rand(1,5)
b

array([[0.48650418, 0.27908802, 0.90948845, 0.32110811, 0.32873635]])

In [ ]:
#Random integers between 1 to 10 with array size of 5
c=np.random.randint(1,10,5)
c

array([4, 4, 9, 1, 6])

In [ ]:
print(c[0:3])

[4 4 9]


In [ ]:
print(np1[0:6:2])

[1 3 5]


In [ ]:
np.shape(np8)

(3, 3, 2)

In [ ]:
#data type
np8.dtype

dtype('float64')

In [ ]:
#Universal Function
print(f" 1.{np.sqrt(np1[1])}")

 1.1.4142135623730951


In [ ]:
# Simulating a "bias" matrix for 2 neurons, each connected to 3 inputs
bias = np.zeros([2,3])
print("Bias matrix:\n", bias)

# Simulating a "mask" (like turning all pixels 'on' in an image)
mask = np.ones([3,3])
print("Mask:\n", mask)


Bias matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
Mask:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

In [ ]:
np21=np.linspace(0,1,3)
np21

array([0. , 0.5, 1. ])

In [ ]:
np22=np.eye(5)
np22

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np23=np.random.randint(0,10,2)
np23

array([2, 2])

In [ ]:
np24=np.eye(5)
np24

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np22+np24

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])